manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 17971b7bf45163e0ef202732290f20b3b46f9743
      import: true

  self:
    path: zephcore
