manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 3e7672a71bd954ca46c38c99d8d8f68a0fb23090
      import: true

  self:
    path: zephcore
