manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 74b7173e9c929cf8eed570fb3df099c5514720c0
      import: true

  self:
    path: zephcore
